name: Format

on:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run rustfmt
        shell: bash
        run: cargo fmt -- --check

      - name: Run clippy
        shell: bash
        run: cargo clippy --all-targets --all-features -- -Dwarnings
